```{r}
library(knitr)
library(dplyr)
library(flextable)
library(magrittr)
library(kableExtra)
library(tidytext)
library(tidyverse)
library(plot.matrix)
library(stringr)
library(micropan)
library(ggpubr)
library(highcharter)
library(ggpubr)
library(tm)
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
library(wordcloud2)
library(viridisLite)
library(Rtsne)
library(qvalue)
library(jaccard)
library(lsa)
load("D:/jazz_visual/0818.RData")
```

```{r}
Mtable = read.csv("D:/jazz_visual/csv/Mtable229.csv", row.names = 1)
M_inst = read.csv("D:/jazz_visual/csv/matrix_instrument.csv", row.names = 1)
M_genre = read.csv("D:/jazz_visual/csv/matrix_genre1.csv", row.names = 1)
M_ysa = read.csv("D:/jazz_visual/csv/matrix_yearsActive.csv", row.names = 1)
ysa = read.csv("D:/jazz_visual/csv/yearsActive.csv", row.names = 1)
M_rl = read.csv("D:/jazz_visual/csv/matrix_recordLabel.csv", row.names = 1)

musicians = rownames(Mtable)
```


# genre
```{r}
cor_genre = cor(M_genre)


plot(cor_genre$w[,1],-cor_genre$w[,2],type="n",xlab="W[,1]",ylab="W[,2]",main="Genre",cex.axis=1.2,cex.lab=1.2,cex.main=1.6)
text(cor_genre$w[,1],-cor_genre$w[,2],cor_genre$namew)
abline(h=0,v=0,lwd=1.2)

cor_genre_plot = as.data.frame(cor_genre$w)
genre = matrix(data = cor_genre$namew, ncol = 1, nrow = 34)
cor_genre_plot = as.data.frame(cbind(cor_genre_plot, genre))
colnames(cor_genre_plot) = c('w1', 'w2', 'genre')
cor_genre_plot = transform(cor_genre_plot, w1 = as.numeric(w1), w2 = as.numeric(w2))

#hchart(cor_genre_plot, 'scatter', hcaes(x = w1, y = -w2, group = genre))
```

```{r}
cor_rl = cor(M_rl)

plot(cor_rl$w[,1],-cor_rl$w[,2],type="n",xlab="W[,1]",ylab="W[,2]",main="Record Label",cex.axis=1.2,cex.lab=1.2,cex.main=1.6)
text(cor_rl$w[,1],-cor_rl$w[,2],cor_rl$namew)
abline(h=0,v=0,lwd=1.2)

```

```{r}
jac_inst = dis_jac(M_inst)
jac_rl = dis_jac(M_rl)
jac_genre = dis_jac(M_genre)
jac_ysa = dis_jac(M_ysa)
```

#t-SNE vs PCA
## Inst
```{r}
set.seed(19970608)
tsne_inst = Rtsne(jac_inst, check_duplicates = FALSE)

pca_inst = prcomp(jac_inst, scale = TRUE,
                center = TRUE, retx = T)

color_inst = read.csv("D:/jazz_visual/csv/color_instclass_sqrt.csv", row.names = 1)
visualTsne_inst = cbind(tsne_inst$Y, color_inst$hex)

colnames(visualTsne_inst) = c('tsne1', 'tsne2', 'hex')
rownames(visualTsne_inst) = musicians
visualTsne_inst = as.data.frame(visualTsne_inst)
visualTsne_inst = transform(visualTsne_inst, tsne1 = as.numeric(tsne1), tsne2 = as.numeric(tsne2))


visualpca_inst = cbind(pca_inst$rotation[,1:2], color_inst$hex)

colnames(visualpca_inst) = c('pc1', 'pc2', 'hex')
rownames(visualpca_inst) = musicians
visualpca_inst = as.data.frame(visualpca_inst)

visualpca_inst = transform(visualpca_inst, pc1 = as.numeric(pc1), pc2 = as.numeric(pc2))

visualTsne_plot = ggplot(visualTsne_inst, aes(x=tsne1, y=tsne2)) +
  geom_point(color = visualTsne_inst$hex)

visualpca_plot = ggplot(visualpca_inst, aes(x=pc1, y=pc2)) +
  geom_point(color = visualpca_inst$hex)
```


```{r}
ComAll = sqrt((jac_genre^2+jac_inst^2+jac_rl^2+jac_ysa^2)/4)
set.seed(19970608)
tsne_ComAll = Rtsne(ComAll, perplexity = 30, eta = 1000, max_iter = 5000, check_duplicates = FALSE)

visualTsne_ComAll = cbind(tsne_ComAll$Y, rownames(Mtable))

colnames(visualTsne_ComAll) = c('tsne1', 'tsne2', 'name')
rownames(visualTsne_ComAll) = musicians
visualTsne_ComAll = as.data.frame(visualTsne_ComAll)

visualTsne_ComAll = transform(visualTsne_ComAll, tsne1 = as.numeric(tsne1), tsne2 = as.numeric(tsne2))

#ggplot(visualTsne_ComAll, aes(x=tsne1, y=tsne2)) +
#  geom_point(color = visualTsne_ComAll$hex)

ggplot(visualTsne_ComAll, aes(x=tsne1, y=tsne2, label=name))+
  geom_point() +geom_text(hjust=0, vjust=0)

hchart(visualTsne_ComAll, 'scatter', hcaes(x=tsne1, y=tsne2, group=name))
```


# zoom in
```{r}
visualTsne_ComAll_WM = zoomin(visualTsne_ComAll, 178)

Wynton = ggplot(visualTsne_ComAll_WM, aes(x=tsne1, y=tsne2, label=name))+
  geom_point() +
  geom_text(hjust=0, vjust=0)+
  xlim(-2,2)+
  ylim(-2,2)

visualTsne_ComAll_RH = zoomin(visualTsne_ComAll, 90)

Roy = ggplot(visualTsne_ComAll_RH, aes(x=tsne1, y=tsne2, label=name))+
  geom_point() +
  geom_text(hjust=0, vjust=0)+
  xlim(-2,2)+
  ylim(-2,2)

visualTsne_ComAll_MD = zoomin(visualTsne_ComAll, 187)

Miles = ggplot(visualTsne_ComAll_MD, aes(x=tsne1, y=tsne2, label=name))+
  geom_point() +
  geom_text(hjust=0, vjust=0)+
  xlim(-2,2)+
  ylim(-2,2)
```


# weight in instrument
```{r}
ComAll.inst = sqrt((jac_genre^2+7*jac_inst^2+jac_rl^2+jac_ysa^2))
set.seed(19970608)
tsne_ComAll.inst = Rtsne(ComAll.inst, perplexity = 30, eta = 1000, max_iter = 5000, check_duplicates = FALSE)

visualTsne_ComAll.inst = cbind(tsne_ComAll.inst$Y, color_inst$hex)

colnames(visualTsne_ComAll.inst) = c('tsne1', 'tsne2', 'hex')
rownames(visualTsne_ComAll.inst) = musicians
visualTsne_ComAll.inst = as.data.frame(visualTsne_ComAll.inst)

visualTsne_ComAll.inst = transform(visualTsne_ComAll.inst, tsne1 = as.numeric(tsne1), tsne2 = as.numeric(tsne2))

#ggplot(visualTsne_ComAll, aes(x=tsne1, y=tsne2)) +
#  geom_point(color = visualTsne_ComAll$hex)

ggplot(visualTsne_ComAll.inst, aes(x=tsne1, y=tsne2))+
  geom_point(color = visualTsne_ComAll.inst$hex)

```


# weight in yearsActive
```{r}
ComAll.ysa = sqrt((jac_genre^2+jac_inst^2+jac_rl^2+7*jac_ysa^2))
set.seed(19970608)
tsne_ComAll.ysa = Rtsne(ComAll.ysa, perplexity = 30, eta = 1000, max_iter = 5000, check_duplicates = FALSE)
visualTsne_ComAll.ysa = cbind(tsne_ComAll.ysa$Y, ysa$year)
colnames(visualTsne_ComAll.ysa) = c('tsne1', 'tsne2', 'year')
rownames(visualTsne_ComAll.ysa) = musicians
visualTsne_ComAll.ysa = as.data.frame(visualTsne_ComAll.ysa)
visualTsne_ComAll.ysa = transform(visualTsne_ComAll.ysa, tsne1 = as.numeric(tsne1), tsne2 = as.numeric(tsne2))

ggplot(visualTsne_ComAll.ysa, aes(x=tsne1, y=tsne2, colour = ysa$year))+
  geom_point()

```