```{r}

x      = read.csv("D:/Jazz_visual/csv/matrix_instrument.csv", row.names = 1)

#x      = x[,3:ncol(x)] 
n      = nrow(x)
p      = ncol(x)

one    = matrix(1,n,n)
h      = diag(1,n,n)-one/n             #centering the matrix
a      = x-matrix(apply(x,2,mean),n,p,byrow=T) #substracts mean
d      = diag(1/sqrt(colSums(a^2)/n))

xs     = h%*%as.matrix(x)%*%d         #standardized data
xs1    = xs/sqrt(n)
xs2    = t(xs1)%*%xs1

eig    = eigen(xs2) #spectral decomposition
lambda = eig$values
gamma  = eig$vectors

w      = gamma*(matrix(sqrt(lambda),nrow=nrow(gamma),ncol=ncol(gamma),byrow=T)) #coordinates of food
w      = w[,1:2]  
w      = round(w,3)

z1     = xs1%*%gamma #coordinates of families
z2     = sqrt(n/p)*z1 
z      = z2[,1:2] 
z      = round(z,3)

namew  = colnames(x)
namez  = rownames(x)

par(mfrow=c(2,2))
plot(w[,1],-w[,2],type="n",xlab="W[,1]",ylab="W[,2]",main="Food",cex.axis=1.2,cex.lab=1.2,cex.main=1.6,xlim=c(-1.2,0.5),ylim=c(-1,0.5))
text(w[,1],-w[,2],namew,xpd=NA)
abline(h=0,v=0,lwd=1.2)

for (i in 1:7){
	mtext(namew[i],side=1,line=5+i,at=-1.15)
 	mtext(toString(c(sprintf("%.3f",w[i,1]))),side=1,line=5+i,at=-.55)
 	mtext(toString(c(sprintf("%.3f",w[i,2]))),side=1,line=5+i,at=0)
 	}

plot(z[,1],-z[,2],type="n",xlim=c(-2,2),ylim=c(-1.1,1),xlab="Z[,1]",ylab="Z[,2]",main="Families",cex.axis=1.2,cex.lab=1.2,cex.main=1.6)
text(z[,1],-z[,2],namez,xpd=NA)
abline(h=0,v=0,lwd=1.2)

for (i in 1:12){
	mtext(namez[i],side=1,line=5+i,at=-2)
 	mtext(toString(c(sprintf("%.3f",z[i,1]))),side=1,line=5+i,at=-1)
 	mtext(toString(c(sprintf("%.3f",z[i,2]))),side=1,line=5+i,at=-0)
 	}
```

```{r}
cor = function(x){
  #x      = x[,3:ncol(x)] 
  n      = nrow(x)
  p      = ncol(x)
  one    = matrix(1,n,n)
  h      = diag(1,n,n)-one/n             #centering the matrix
  a      = x-matrix(apply(x,2,mean),n,p,byrow=T) #substracts mean
  d      = diag(1/sqrt(colSums(a^2)/n))
  xs     = h%*%as.matrix(x)%*%d         #standardized data
  xs1    = xs/sqrt(n)
  xs2    = t(xs1)%*%xs1
  eig    = eigen(xs2) #spectral decomposition
  lambda = eig$values
  gamma  = eig$vectors
  w      = gamma*(matrix(sqrt(lambda),nrow=nrow(gamma),ncol=ncol(gamma),byrow=T)) #coordinates of food
  w      = w[,1:2]  
  w      = round(w,3)
  z1     = xs1%*%gamma #coordinates of families
  z2     = sqrt(n/p)*z1 
  z      = z2[,1:2] 
  z      = round(z,3)
  namew  = colnames(x)
  namez  = rownames(x)
  par(mfrow=c(2,2))
  plot(w[,1],-w[,2],type="n",main="Food",cex.axis=1.2  ,cex.lab=1.2,cex.main=1.6,xlim=c(-1.2,0.5),ylim=c(-1,0.5))
  text(w[,1],-w[,2],namew,xpd=NA)
  abline(h=0,v=0,lwd=1.2)
  
  for (i in 1:7){
  	mtext(namew[i],side=1,line=5+i,at=-1.15)
   	mtext(toString(c(sprintf("%.3f",w[i,1]))),side=1,line=5+i,at=-.55)
   	mtext(toString(c(sprintf("%.3f",w[i,2]))),side=1,line=5+i,at=0)
   	}
  
  plot(z[,1],-z[,2],type="n",xlab="Z[,1]",ylab="Z[,  2]",main="Families",cex.axis=1.2,cex.lab=1.2,cex.main=1.6)
  text(z[,1],-z[,2],namez,xpd=NA)
  abline(h=0,v=0,lwd=1.2)
  
  for (i in 1:12){
  	mtext(namez[i],side=1,line=5+i,at=-2)
   	mtext(toString(c(sprintf("%.3f",z[i,1]))),side=1,line=5+i,at=-1)
   	mtext(toString(c(sprintf("%.3f",z[i,2]))),side=1,line=5+i,at=-0)
   	}
  return(list(w = w, z = z, namew = namew, namez = namez))
}
```

```{r}
x_cor = cor(x)
```