```{r}
M_genre = read.csv("D:/jazz_visual/csv/matrix_genre1hp.csv", row.names = 1)
musicians = rownames(M_genre)

M_ysa = read.csv("D:/jazz_visual/csv/matrix_yearsActive_i.csv", row.names = 1)
M_ysamid = read.csv("D:/jazz_visual/csv/matrix_yearsActive_mid.csv", row.names = 1)
M_ysalen = read.csv("D:/jazz_visual/csv/matrix_yearsActive_len.csv", row.names = 1)

M_rl = read.csv("D:/jazz_visual/csv/matrix_recordLabel.csv", row.names = 1)

M_inst = read.csv("D:/jazz_visual/csv/matrix_instrument.csv", row.names = 1)

# Jaccard function
dis_jac = function(M){
  M = as.matrix(M)
  library("jaccard")
  n = nrow(M)
  # n*n matrix
  af_matrix = matrix(data = 1, nrow = n, ncol = n)
  for(i in 1:(n-1)){
    for(j in (i+1):n){
      if(sum(M[i,])==0&sum(M[j,])==0){
        jac = 0
        af_matrix[i,j] = af_matrix[j,i] = jac
      }else{
        jac = jaccard(M[i,],M[j,])
        af_matrix[i,j] = af_matrix[j,i] = jac
      }
    }
  }
  colnames(af_matrix) = rownames(af_matrix) = rownames(M)
  return(as.data.frame(af_matrix))
}

# Jaccard function
dis_jac.c = function(M, C=0){
  M = as.matrix(M)
  library("jaccard")
  n = nrow(M)
  # n*n matrix
  jaccard.c = function (x, y, c=0, center = FALSE, px = NULL, py = NULL) 
  {
    if (length(x) != length(y)) {
      stop("Two fingerprints (x and y) must be of the same length.")
    }
    if (is.null(px) | is.null(py)) {
      px <- mean(x)
      py <- mean(y)
    }
    sumxy <- sum(x & y)+c
    unionxy <- sum(x) + sum(y) - sumxy+2*c
    if (unionxy == 0) {
      j <- (px * py)/(px + py - px * py)
    }
    else {
      j <- sumxy/unionxy
    }
    if (center == FALSE) {
      return(j)
    }
    else {
      return(j - (px * py)/(px + py - px * py))
    }
  }
  af_matrix = matrix(data = 1, nrow = n, ncol = n)
  for(i in 1:(n-1)){
    for(j in (i+1):n){
      if(sum(M[i,])==0&sum(M[j,])==0){
        jac = 0
        af_matrix[i,j] = af_matrix[j,i] = jac
      }else{
        jac = jaccard.c(M[i,],M[j,], c=C)
        af_matrix[i,j] = af_matrix[j,i] = jac
      }
    }
  }
  colnames(af_matrix) = rownames(af_matrix) = rownames(M)
  return(as.data.frame(af_matrix))
}


jaccard.c = function (x, y, c=0, center = FALSE, px = NULL, py = NULL) 
{
  if (length(x) != length(y)) {
    stop("Two fingerprints (x and y) must be of the same length.")
  }
  if (is.null(px) | is.null(py)) {
    px <- mean(x)
    py <- mean(y)
  }
  sumxy <- sum(x & y)+c
  unionxy <- sum(x) + sum(y) - sumxy+2*c
  if (unionxy == 0) {
    j <- (px * py)/(px + py - px * py)
  }
  else {
    j <- sumxy/unionxy
  }
  if (center == FALSE) {
    return(j)
  }
  else {
    return(j - (px * py)/(px + py - px * py))
  }
}

```

```{r}
Jac_ysa = dis_jac(M_ysa)
Jac_ysamid = dis_jac(M_ysamid)
Jac_ysalen = dis_jac(M_ysalen)
Jac_genre = dis_jac(M_genre)
Jac_rl = dis_jac(M_rl)
Jac_inst = dis_jac(M_inst)

# new version
con=1
Jacc_ysa = dis_jac.c(M_ysa, C=con)
Jacc_ysamid = dis_jac.c(M_ysamid, C=con)
Jacc_ysalen = dis_jac.c(M_ysalen, C=con)
Jacc_genre = dis_jac.c(M_genre, C=con)
Jacc_rl = dis_jac.c(M_rl, C=con)
Jacc_inst = dis_jac.c(M_inst, C=con)
```

```{r}
Dist_ysa = 1-Jac_ysa
Dist_ysamid = 1-Jac_ysamid
Dist_ysalen = 1-Jac_ysalen
Dist_genre = 1-Jac_genre
Dist_rl = 1-Jacc_rl
Dist_inst = 1-Jac_inst

Distc_ysa = 1-Jacc_ysa
Distc_ysamid = 1-Jacc_ysamid
Distc_ysalen = 1-Jacc_ysalen
Distc_genre = 1-Jacc_genre
Distc_rl = 1-Jacc_rl
Distc_inst = 1-Jacc_inst
```

# combined all

```{r}


Dist_all = sqrt((0.3*Dist_ysa^2+0.3*Dist_ysamid^2+0.3*Dist_ysalen^2+Dist_genre^2+Dist_rl^2+Dist_inst^2))

Dist_all.ysamid = sqrt((0.3*Dist_ysa^2+2*Dist_ysamid^2+0.3*Dist_ysalen^2+Dist_genre^2+Dist_rl^2+Dist_inst^2))

Dist_all.ysalen = sqrt((0.3*Dist_ysa^2+0.3*Dist_ysamid^2+2*Dist_ysalen^2+Dist_genre^2+Dist_rl^2+Dist_inst^2))

Dist_all.genre = sqrt((0.3*Dist_ysa^2+0.3*Dist_ysamid^2+0.3*Dist_ysalen^2+8*Dist_genre^2+Dist_rl^2+Dist_inst^2))

Dist_all.rl = sqrt((0.3*Dist_ysa^2+0.3*Dist_ysamid^2+0.3*Dist_ysalen^2+Dist_genre^2+8*Dist_rl^2+Dist_inst^2))

Dist_all.inst = sqrt((0.3*Dist_ysa^2+0.3*Dist_ysamid^2+0.3*Dist_ysalen^2+Dist_genre^2+Dist_rl^2+8*Dist_inst^2))

# new version
Distc_all = sqrt((0.3*Distc_ysa^2+0.3*Distc_ysamid^2+0.3*Distc_ysalen^2+Distc_genre^2+Distc_rl^2+Distc_inst^2))

Distc_all.ysamid = sqrt((0.3*Distc_ysa^2+2*Distc_ysamid^2+0.3*Distc_ysalen^2+Distc_genre^2+Distc_rl^2+Distc_inst^2))

Distc_all.ysalen = sqrt((0.3*Distc_ysa^2+0.3*Distc_ysamid^2+2*Distc_ysalen^2+Distc_genre^2+Distc_rl^2+Distc_inst^2))

Distc_all.genre = sqrt((0.3*Distc_ysa^2+0.3*Distc_ysamid^2+0.3*Distc_ysalen^2+8*Distc_genre^2+Distc_rl^2+Distc_inst^2))

Distc_all.rl = sqrt((0.3*Distc_ysa^2+0.3*Distc_ysamid^2+0.3*Distc_ysalen^2+Distc_genre^2+8*Distc_rl^2+Distc_inst^2))

Distc_all.inst = sqrt((0.3*Distc_ysa^2+0.3*Distc_ysamid^2+0.3*Distc_ysalen^2+Distc_genre^2+Distc_rl^2+8*Distc_inst^2))
```

```{r}
ls()
```

```{r}
rm(list = ls()[c(1:15,22:46)])
```