```{r}
Mtable = read.csv('D:/jazz_visual/csv/Mtable229.csv', row.names = 1)

RL = as.data.frame(Mtable$recordLabel)
colnames(RL) = 'record_label'
rownames(RL) = rownames(Mtable)
```

# record label
```{r}
RL_split = token_split(RL, g=1)
RL_ohe = oh_encoding(RL, tok = RL_split$token_list1)
RL_matrix = RL_ohe$token_matrix

RL_del_col = c()
for(i in 1:ncol(RL_matrix)){
  sum_mu = sum(RL_matrix[,i])
  if(sum_mu==1){
    print(sprintf("%s:%s", i, colnames(RL_matrix)[i]))
    RL_del_col = cbind(RL_del_col, i)
  }
}
```

```{r}
# Multivalue check
RL_matrix1 = RL_matrix[,-RL_del_col]
RL_list = colnames(RL_matrix1)
for(i in 1:nrow(RL_matrix1)){
  sum_mu = sum(RL_matrix1[i,])
  if(sum_mu>1){
    print(sprintf("Multivlaue in %s: %s", i, rownames(RL_matrix1)[i]))
  }
}
```

```{r}
write.csv(RL_matrix1, 'D:/jazz_visual/csv/matrix_recordLabel.csv', na="")
write.csv(colnames(M_rl), 'D:/jazz_visual/csv/list_recordLabel.csv')
```

```{r}

for(i in 1:nrow(M_rl)){
  sum_mu = sum(M_rl[i,])
  if(sum_mu>1){
    print(sprintf("Multivlaue in %s: %s", i, rownames(M_rl)[i]))
    print(sum_mu)
  }
}

M_rl.hp = M_rl[,-c(84:89)]

for(i in 1:nrow(M_rl.hp)){
  sum_mu = sum(M_rl.hp[i,])
  if(sum_mu>1){
    print(sprintf("Multivlaue in %s: %s", i, rownames(M_rl.hp)[i]))
    print(sum_mu)
  }
}
```

```{r}
cor_rl.hp = cor(M_rl.hp)

plot(cor_rl.hp$w[,1],-cor_rl.hp$w[,2],type="n",xlab="W[,1]",ylab="W[,2]",main="Record Label",cex.axis=1.2,cex.lab=1.2,cex.main=1.6)
text(cor_rl.hp$w[,1],-cor_rl.hp$w[,2],cor_rl.hp $namew)
abline(h=0,v=0,lwd=1.2)
```

```{r}
M_recordLabel = read.csv("D:/jazz_visual/csv/matrix_recordLabel.csv", row.names = 1)
recordLabel = colnames(M_recordLabel)
```

```{r}
Jac_recordLabel.t = dis_jac(t(M_recordLabel))
```


```{r}
PCA_recordLabel = prcomp(Jac_recordLabel.t, center = TRUE, scale. = TRUE)
```

```{r}
plot(PCA_recordLabel$rotation[,1],PCA_recordLabel$rotation[,2],type="n",xlab="PC1",ylab="PC2",main="Record Label",cex.axis=1.2,cex.lab=1.2,cex.main=1.6)
text(PCA_recordLabel$rotation[,1],PCA_recordLabel$rotation[,2],recordLabel)
abline(h=0,v=0,lwd=1.2)
```