---
title: "**Visualization for Jazz Musicians**"
format:
  revealjs:
    incremental: true
    theme: moon
author: "*Yi-Hsin Lu*"
date: "Jan. 10th, 2023"
---

## Outline

-   **Introduction**

-   **The Data**

-   **Formulation**

-   **Results**

-   **Conclusions**

# Introduction

## Visualization

-   Why is visualization so important?

## Jazz Musician

-   Why we chose jazz musicians?

## Dataset

-   DBpedia

# Data

## Database

## Collection

```{r echo=FALSE}
library(kableExtra)
load("ThesisP_dataset.RData")
kbl(JazzMusiciansData[c(178,90,1:6),],align = "l", row.names = T) %>%
  kable_paper("striped", full_width = F) %>%
  row_spec(0, bold = T, font_size = 24)%>%
  kable_styling(fixed_thead = T, font_size = 18)%>%
  kable_material_dark()
rm(list = ls())
```

## Text Mining

## Data Matrix

# Formulations

## Flow Chart

# Instruments

## Encoding

## Jaccard

# Genres

## Encoding

## Jaccard

# Active Years

-   The Start of Active Years

-   The End of Active Years

-   Active Years Interval

-   Length of Active Years

-   Middle of Active Years

## Encoding

## Jaccard

# Multi-value Classification

-   Instruments

-   Genres

## Principle Component Analysis

## Groups

## Coloring

# Combination

-   Affinity matrices

    -   Instruments

    -   Genres

    -   Active Years

    -   Length of Active Years

    -   Middle of Active Years

## Distance/Similarity

## Tuning

# Results

# Visualization

-   Dimensionality Reduction

-   **P**rinciple **C**omponent **A**nalysis (PCA)

-   **t**-distributed **S**tochastic **N**eighbor **E**mbedding (t-SNE)

# Conclusions

# References
